version: '3'
services:
  web:
    image: "prometeo:0.0.1-0"
    environment:
     - HTTP_PORT=8080
     - LOG_DB_HOST=log
     - LOG_DB_PORT=27017
     - LOG_DB_NAME=prometeo
    ports:
     - "8080:8080"
    links:
     - log
  log:
    image: "mongo"
    ports:
     - "27017:27017"